name: array-filters
# on: workflow_dispatch  
on: 
  - push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.job1.outputs.matrix).*.project }}
    steps:
      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"

  # produce_output:
  #   name: Try array stuff
  #   permissions:
  #     contents: read
  #   runs-on: ubuntu-latest
  #   env:
  #     OUTPUT: '{ "list_one":  [{"name": "foo"}] "list_two":  [{"name": "bar"}] }'
  #   steps:
  #     - name: produce object output
  #       run: |
  #           echo "content=${OUTPUT}"
  #           echo "content=${OUTPUT}" >> $GITHUB_OUTPUT

  # use_output:
  #   permissions: 
  #     contents: read
  #   runs-on: ubuntu-latest
  #   needs: produce_output
  #   steps:
  #     - name: Munge list 
  #       run: |
  #         echo "output=${{ toJson(needs.produce_output.output.content) }}" >> $GITHUB_OUTPUT
  #         echo "output=${{ needs.produce_output.output.content }}" >> $GITHUB_OUTPUT
        
  
    
  # includes:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
          