name: array-filters
on: workflow_dispatch  

jobs: 
  produce_output:
    name: Try array stuff
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      OUTPUT: '{ "list_one":  [{"name": "foo"}] "list_two":  [{"name": "bar"}] }'
    steps:
      - name: produce object output
        run: |
            echo "content=${OUTPUT}"
            echo "content=${OUTPUT}" >> $GITHUB_OUTPUT

  use_output:
    permissions: 
      contents: read
    runs-on: ubuntu-latest
    needs: produce_output
    steps:
      - name: Munge list 
        run: |
          echo "output=${{ needs.produce_output.output }}"" >> $GITHUB_OUTPUT
        
  
    
  # includes:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
          